api_version = "2025-01"

[[extensions]]
name = "t:name"
handle = "product-fixed-discount-by-tag"

uid = "c6cd3e19-514e-d5c8-82f6-70a0e7aee745494fd022"

type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/product_fixed_discount_by_tag/:functionId/new"
  details = "/app/product_fixed_discount_by_tag/:functionId/:id"

 [extensions.input.variables]
namespace = "$app:product-discount"
key = "JsonTag" 
