api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "bundle-set-price"
type = "function"
uid = "b66e1a7c-cdb4-4554-e536-12fa92ec27edda62ad06"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
