# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3109de6648b3f3d52798f8fd758d859e"
application_url = "https://shopify-func-app-5b1a9e5cd4bd.herokuapp.com"
embedded = true
name = "Function-app"
handle = "function-app-18"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts"

[auth]
redirect_urls = [
  "https://shopify-func-app-5b1a9e5cd4bd.herokuapp.com/auth/callback",
  "https://shopify-func-app-5b1a9e5cd4bd.herokuapp.com/auth/shopify/callback",
  "https://shopify-func-app-5b1a9e5cd4bd.herokuapp.com/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
